-- Supabase SQL Editor'da bu dosyanın tamamını bir kez çalıştırın.
-- Bu MVP özellikle herkesin aynı veriye erişmesi istendiği için anonim okuma/yazmayı açar.
-- Hassas veri saklamayın. Üretimde kullanıcı girişi ve daha dar RLS politikaları ekleyin.

create table if not exists public.products (
  barcode text primary key,
  name text not null,
  brand text not null default '',
  image_url text not null default '',
  source text not null default 'manual',
  updated_at timestamptz not null default now()
);

create table if not exists public.count_entries (
  id bigint generated by default as identity primary key,
  session_name text not null default 'Genel Sayım',
  barcode text not null,
  product_name text not null,
  brand text not null default '',
  quantity integer not null check (quantity > 0 and quantity <= 100000),
  counted_by text not null default 'İsimsiz',
  created_at timestamptz not null default now()
);

-- A101'de ilk denemede bulunmayan barkodlar burada bekler.
-- Uygulamayı kullanan herhangi bir çevrim içi telefon bu kuyruğu işler,
-- bulunan ürünü products tablosuna yazar ve kuyruk kaydını siler.
create table if not exists public.product_lookup_queue (
  barcode text primary key,
  name_hint text not null default '',
  brand_hint text not null default '',
  status text not null default 'pending' check (status in ('pending', 'processing', 'failed')),
  attempts integer not null default 0 check (attempts >= 0),
  next_attempt_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists count_entries_session_idx
  on public.count_entries (session_name, created_at desc);

create index if not exists count_entries_barcode_idx
  on public.count_entries (barcode);

create index if not exists product_lookup_queue_pending_idx
  on public.product_lookup_queue (status, next_attempt_at, updated_at);

alter table public.products enable row level security;
alter table public.count_entries enable row level security;
alter table public.product_lookup_queue enable row level security;

drop policy if exists "Public products read" on public.products;
drop policy if exists "Public products insert" on public.products;
drop policy if exists "Public products update" on public.products;
drop policy if exists "Public products delete" on public.products;
drop policy if exists "Public counts read" on public.count_entries;
drop policy if exists "Public counts insert" on public.count_entries;
drop policy if exists "Public counts update" on public.count_entries;
drop policy if exists "Public counts delete" on public.count_entries;
drop policy if exists "Public lookup queue read" on public.product_lookup_queue;
drop policy if exists "Public lookup queue insert" on public.product_lookup_queue;
drop policy if exists "Public lookup queue update" on public.product_lookup_queue;
drop policy if exists "Public lookup queue delete" on public.product_lookup_queue;

create policy "Public products read" on public.products for select to anon using (true);
create policy "Public products insert" on public.products for insert to anon with check (true);
create policy "Public products update" on public.products for update to anon using (true) with check (true);
create policy "Public products delete" on public.products for delete to anon using (true);

create policy "Public counts read" on public.count_entries for select to anon using (true);
create policy "Public counts insert" on public.count_entries for insert to anon with check (true);
create policy "Public counts update" on public.count_entries for update to anon using (true) with check (true);
create policy "Public counts delete" on public.count_entries for delete to anon using (true);

create policy "Public lookup queue read" on public.product_lookup_queue for select to anon using (true);
create policy "Public lookup queue insert" on public.product_lookup_queue for insert to anon with check (true);
create policy "Public lookup queue update" on public.product_lookup_queue for update to anon using (true) with check (true);
create policy "Public lookup queue delete" on public.product_lookup_queue for delete to anon using (true);

grant usage on schema public to anon;
grant select, insert, update, delete on public.products to anon;
grant select, insert, update, delete on public.count_entries to anon;
grant select, insert, update, delete on public.product_lookup_queue to anon;
grant usage, select on all sequences in schema public to anon;

-- Realtime güncellemeleri için tabloyu yayına ekler.
do $$
begin
  alter publication supabase_realtime add table public.count_entries;
exception
  when duplicate_object then null;
end $$;
